"""Versioned constants shared across World Factory modules."""

SCHEMA_VERSION = "11.0.0"
MODEL_VERSION = "phase-3.1"
DETERMINISTIC_ALGORITHM_VERSION = "tectonic-plates-v1"
HYDROLOGY_ALGORITHM_VERSION = "flow-routing-v1"
ATMOSPHERE_ALGORITHM_VERSION = "wind-belts-v1"
ASTRONOMY_ALGORITHM_VERSION = "axial-tilt-v1"
GEOLOGY_SUBLEYER_ALGORITHM_VERSION = "rock-ore-soil-v1"
BIOLOGY_ALGORITHM_VERSION = "biome-biota-v1"
SETTLEMENTS_ALGORITHM_VERSION = "candidate-scoring-v1"
CANONICAL_DEMO_SEED = 42
MINIMUM_SEED = 0
MAXIMUM_SEED = (1 << 64) - 1
MINIMUM_ELEVATION_METERS = -11_000.0
MAXIMUM_ELEVATION_METERS = 9_000.0
MINIMUM_SURFACE_TEMPERATURE_CELSIUS = -120.0
MAXIMUM_SURFACE_TEMPERATURE_CELSIUS = 80.0
MINIMUM_OCEAN_FRACTION = 0.1
MAXIMUM_OCEAN_FRACTION = 0.9
STANDARD_ATMOSPHERIC_PRESSURE_KPA = 101.325
MINIMUM_ATMOSPHERIC_PRESSURE_KPA = 1.0
ATMOSPHERIC_SCALE_HEIGHT_METERS = 8_400.0
MINIMUM_PLATE_COUNT = 3
MAXIMUM_PLATE_COUNT = 64
MINIMUM_PLATE_INTERIOR_CELL_COUNT = 4
CONVERGENT_BOUNDARY_UPLIFT_METERS = 4_800.0
DIVERGENT_BOUNDARY_RIFT_METERS = -2_400.0
CONTINENTAL_INTERIOR_BASE_ELEVATION_METERS = 900.0
OCEANIC_INTERIOR_BASE_ELEVATION_METERS = -1_200.0
ELEVATION_NOISE_RANGE_METERS = 1_000.0
MINIMUM_HEADWATER_BASIN_CELLS = 4
MINIMUM_RUNOFF_PRECIPITATION_MM = 250.0
MINIMUM_HEADWATER_ELEVATION_METERS = 750.0
RUNOFF_COEFFICIENT = 0.35
GRID_CELL_AREA_KILOMETERS_SQUARED = 80.0
MILLIMETERS_PER_YEAR_PER_CELL_KILOMETER_SQUARED = 1.0
HYDROLOGY_DISCHARGE_SCALE = 1.0e-6
MAXIMUM_SPECIFIC_HUMIDITY_KG_PER_KG = 0.030
WIND_BELT_HADLEY_DEGREES = 30.0
WIND_BELT_FERREL_DEGREES = 60.0
SEA_BREEZE_TEMPERATURE_DELTA_CELSIUS = 4.0
EVAPORATION_WIND_COEFFICIENT = 0.06
TRANSPORT_ITERATIONS = 32
BASE_PRECIPITATION_LOSS = 0.04
OROGRAPHIC_BOOST_DIVISOR_METERS = 1_000.0
PRESSURE_HUMIDITY_BUOYANCY = 0.01
PRECIPITATION_REFINEMENT_BLEND = 0.5
SEASONAL_TEMPERATURE_AMPLITUDE = 0.10
EARTH_AXIAL_TILT_DEGREES = 23.5
EARTH_ORBITAL_ECCENTRICITY = 0.0167
EARTH_ROTATION_PERIOD_HOURS = 24.0
EARTH_ORBITAL_PERIOD_DAYS = 365.25
MINIMUM_ORE_PROBABILITY = 0.10
ORE_PROBABILITY_SCALE = 0.4
SEDIMENTARY_ELEVATION_CAP_METERS = 500.0
PEAT_PRECIPITATION_THRESHOLD_MM = 1_400.0
LOAM_PRECIPITATION_THRESHOLD_MM = 350.0
PERMAFROST_TEMPERATURE_CELSIUS = -10.0
SETTLEMENT_CANDIDATE_GRID_DIVISOR = 16
SETTLEMENT_MIN_COUNT = 20
SETTLEMENT_PER_PLATE_COUNT = 3
SETTLEMENT_MIN_SPACING_CELLS = 4
SETTLEMENT_DEFENSIBILITY_LOW_METERS = 200.0
SETTLEMENT_DEFENSIBILITY_HIGH_METERS = 1500.0
SETTLEMENT_CLIMATE_LOW_CELSIUS = 5.0
SETTLEMENT_CLIMATE_HIGH_CELSIUS = 25.0
SETTLEMENT_POPULATION_ARABLE_BASE = 1000
SETTLEMENT_POPULATION_WATER_BONUS = 500
SETTLEMENT_POPULATION_MINERAL_BONUS = 200
SETTLEMENT_DEFENSIBILITY_RAMP_METERS = 1500.0
SETTLEMENT_CLIMATE_RAMP_COLD_CELSIUS = 25.0
SETTLEMENT_CLIMATE_RAMP_HOT_CELSIUS = 20.0
SETTLEMENT_CLIMATE_LOWER_BOUND_CELSIUS = -20.0
SETTLEMENT_WATER_DECAY_DIVISOR = 8.0
AGRICULTURE_ALGORITHM_VERSION = "caloric-accounting-v1"
AGRICULTURE_EXTRACTION_RADIUS_CELLS = 10
AGRICULTURE_BASE_YIELD_TONNES_PER_CELL = 4.0
AGRICULTURE_PRECIPITATION_OPTIMUM_MM = 1_000.0
AGRICULTURE_TEMPERATURE_OPTIMUM_CELSIUS = 18.0
AGRICULTURE_TEMPERATURE_RANGE_CELSIUS = 18.0
AGRICULTURE_SOIL_QUALITY = {
    "loam": 1.0,
    "clay": 0.7,
    "peat": 0.5,
    "sand": 0.3,
    "permafrost": 0.0,
}
AGRICULTURE_BIOME_QUALITY = {
    "temperate-forest": 1.0,
    "grassland": 0.9,
    "tropical-forest": 0.8,
    "desert": 0.1,
    "alpine": 0.1,
    "ice": 0.0,
    "ocean": 0.0,
}
AGRICULTURE_CALORIC_KCAL_PER_TONNE = 3_000_000.0
AGRICULTURE_KCAL_PER_PERSON_PER_YEAR = 800_000.0
AGRICULTURE_DEFICIT_YIELD_FRACTION = 0.25
AGRICULTURE_MINIMUM_ARABLE_CELLS = 1
INFRASTRUCTURE_ALGORITHM_VERSION = "min-cost-friction-v1"
INFRASTRUCTURE_IMPASSABLE = 1.0e9
INFRASTRUCTURE_BASE_FRICTION_PER_BIOME = {
    "grassland": 1.0,
    "temperate-forest": 1.5,
    "tropical-forest": 1.7,
    "desert": 2.0,
    "alpine": 2.5,
    "ice": 1.0e9,
    "ocean": 1.0e9,
}
INFRASTRUCTURE_SLOPE_PENALTY_PER_METER = 0.0015
INFRASTRUCTURE_RIVER_CROSSING_PENALTY = 6.0
INFRASTRUCTURE_DIAGONAL_COST = 1.4142135623730951
INFRASTRUCTURE_ROAD_NEIGHBOR_K = 3
INFRASTRUCTURE_COASTAL_RADIUS_CELLS = 1
INFRASTRUCTURE_RIVER_PROXIMITY_RADIUS_CELLS = 2
INFRASTRUCTURE_PORT_TONNAGE_THRESHOLD = 1.0
INFRASTRUCTURE_PORT_TONNAGE_PER_POPULATION = 1.0
INFRASTRUCTURE_MAX_CANALS = 8
INFRASTRUCTURE_CANAL_SLOPE_LIMIT_M_PER_CELL = 5000.0
INFRASTRUCTURE_CANAL_MIN_FLOW = 50_000_000.0
DEMOGRAPHY_ALGORITHM_VERSION = "aggregate-pools-v1"
DEMOGRAPHY_DEFAULT_TIME_STEPS = 50
DEMOGRAPHY_BASE_BIRTH_RATE = 0.04
DEMOGRAPHY_BASE_DEATH_RATE = 0.03
DEMOGRAPHY_CAPACITY_HEADROOM_BIRTH_BOOST = 0.02
DEMOGRAPHY_OVER_CAPACITY_DEATH_PENALTY = 0.02
DEMOGRAPHY_CLIMATE_OPTIMUM_CELSIUS = 18.0
DEMOGRAPHY_CLIMATE_RANGE_CELSIUS = 18.0
DEMOGRAPHY_CONFLICT_THRESHOLD = 0.6
DEMOGRAPHY_CONFLICT_DEATH_MULTIPLIER = 1.5
DEMOGRAPHY_MIGRATION_PRESSURE_FACTOR = 0.10
DEMOGRAPHY_MIGRATION_PULL_FACTOR = 0.05
DEMOGRAPHY_MIGRATION_COST_DIVISOR = 50.0