"""Versioned constants shared across World Factory modules."""

SCHEMA_VERSION = "1.0.0"
MODEL_VERSION = "phase-0.1"
DETERMINISTIC_ALGORITHM_VERSION = "blake2b-grid-v1"
CANONICAL_DEMO_SEED = 42
MINIMUM_SEED = 0
MAXIMUM_SEED = (1 << 64) - 1
MINIMUM_ELEVATION_METERS = -11_000.0
MAXIMUM_ELEVATION_METERS = 9_000.0
MINIMUM_SURFACE_TEMPERATURE_CELSIUS = -120.0
MAXIMUM_SURFACE_TEMPERATURE_CELSIUS = 80.0
MINIMUM_OCEAN_FRACTION = 0.1
MAXIMUM_OCEAN_FRACTION = 0.9
STANDARD_ATMOSPHERIC_PRESSURE_KPA = 101.325
