//! Event System for World Factory
//! 
//! Defines historical events, event types, and event effects.
//! Events are the primary mechanism for history generation and timeline construction.
//!
//! ## Event Lifecycle
//! 
//! 1. **Creation** — Event generated by a system (settlement, war, discovery, etc.)
//! 2. **Application** — Event effects applied to world state (population change, border shift, etc.)
//! 3. **Timeline Insertion** — Event inserted into chronological timeline
//! 4. **Consequence Triggering** — Secondary events may be triggered by consequences
//!
//! ## EventType Categories
//! 
//! | Category | Types | Description |
//! |----------|-------|-------------|
//! | Political | Founding, Treaty, Reform, Succession, Alliance | Governance and diplomacy |
//! | Military | War, Battle, Siege, Conquest, Raid | Armed conflict events |
//! | Natural | Plague, Famine, Earthquake, Flood, Drought, Volcano | Environmental disasters |
//! | Cultural | Festival, Art, Invention, Migration, Immigration | Social and cultural shifts |
//! | Discovery | Exploration, Discovery, FirstContact, Invention | Knowledge advancement |
//! | Catastrophe | Collapse, Destruction, Extinction, MeteorStrike | Major disruptive events |
//!
//! ## Usage Example
//! 
//! ```rust
//! use world_factory::events::{Event, EventBuilder, HistoricalTime, EventEffect};
//! 
//! let event = EventBuilder::new("The Great Plague")
//!     .event_type(EventType::Plague)
//!     .time(HistoricalTime::year(1347))
//!     .location(region_id)
//!     .participant(settlement_id)
//!     .effect(EventEffect::PopulationLoss { target: settlement_id, amount: 10000, duration_years: Some(50), cause: Some("The Great Plague".to_string()) })
//!     .build(world_id);
//! ```

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use crate::types::{EntityId, EntityType, Timestamp, HistoricalTime};

pub mod event_type;
pub mod effect;
pub mod timeline;
pub mod probability;

pub use event_type::{EventType, EventCategory};
pub use effect::{EventEffect, EffectMagnitude, MilitaryChangeType, LeadershipChangeType, DiplomaticChangeType, EconomicChangeType, ResourceChangeType, CulturalChangeType, ReligiousChangeType, TechnologicalChangeType, EnvironmentalChangeType};
pub use timeline::{EventTimeline, TimelineSlice, TimelineStats};
pub use probability::{ProbabilityEngine, ProbabilityConfig, EventContext, EffectApplicator, EventPredictor, ProbabilityResult, EffectApplicationResult, SecondaryEventProcessor, SecondaryEventQueue, SecondaryEventCandidate, TriggerRule, default_trigger_rules};

// ============================================================================
// Event Core
// ============================================================================

/// A historical event in the world timeline.
/// 
/// Events are the atomic units of history — they occur at a specific time,
/// in a specific location, with specific participants and effects.
/// 
/// # Example
/// 
/// ```rust
/// use world_factory::events::{Event, EventBuilder, EventType, HistoricalTime, EventEffect};
/// use uuid::Uuid;
/// 
/// let world_id = Uuid::new_v4();
/// let settlement_id = Uuid::new_v4();
/// 
/// let plague = EventBuilder::new("The Great Plague")
///     .event_type(EventType::Plague)
///     .time(HistoricalTime::year(1347))
///     .end_time(HistoricalTime::year(1351))
///     .location(settlement_id)
///     .participant(settlement_id)
///     .effect(EventEffect::PopulationLoss {
///         target: settlement_id,
///         amount: 1000000,
///         duration_years: Some(50),
///         cause: Some("Bubonic plague swept across the continent".to_string()),
///     })
///     .significance(0.80)
///     .build(world_id);
/// ```
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Event {
    /// Unique identifier for this event.
    pub id: EntityId,
    
    /// The world this event belongs to.
    pub world_id: Uuid,
    
    /// Human-readable name of the event.
    pub name: String,
    
    /// Detailed description of what happened.
    pub description: String,
    
    /// The type/category of this event (from comprehensive EventType enum).
    #[serde(rename = "type")]
    pub event_type: EventType,
    
    /// When this event began.
    pub time: HistoricalTime,
    
    /// When this event ended (for ongoing/duration events).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub end_time: Option<HistoricalTime>,
    
    /// Geographic location where this event occurred.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub location_id: Option<Uuid>,
    
    /// Entities involved in this event (settlements, nations, persons).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub participants: Option<Vec<Uuid>>,
    
    /// What happened as a result of this event.
    pub effects: Vec<EventEffect>,
    
    /// Secondary events triggered by this event.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub consequences: Option<Vec<String>>,
    
    /// Historical significance (0.0 to 1.0). Major wars = 0.9+, local gossip = 0.1.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub significance: Option<f32>,
    
    /// Primary sources/references for this event (historical texts, legends).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sources: Option<Vec<String>>,
    
    pub created_at: Timestamp,
    pub updated_at: Timestamp,
}

impl Event {
    /// Create a new event with required fields.
    pub fn new(
        world_id: Uuid,
        name: String,
        description: String,
        event_type: EventType,
        time: HistoricalTime,
    ) -> Self {
        let now = Timestamp::now();
        Self {
            id: EntityId::new(EntityType::Event),
            world_id,
            name,
            description,
            event_type,
            time,
            end_time: None,
            location_id: None,
            participants: None,
            effects: Vec::new(),
            consequences: None,
            significance: None,
            sources: None,
            created_at: now,
            updated_at: now,
        }
    }
    
    /// Create a settlement founded event.
    pub fn settlement_founded(
        world_id: Uuid,
        _settlement_id: Uuid,
        settlement_name: &str,
        time: HistoricalTime,
    ) -> Self {
        Self::new(
            world_id,
            format!("{} Founded", settlement_name),
            format!("The settlement of {} was established.", settlement_name),
            EventType::SettlementFounded,
            time,
        )
    }
    
    /// Create a war declared event.
    pub fn war_declared(
        world_id: Uuid,
        war_name: &str,
        attacker_id: Uuid,
        defender_id: Uuid,
        time: HistoricalTime,
    ) -> Self {
        let mut event = Self::new(
            world_id,
            format!("War Declared: {}", war_name),
            format!("War was declared between two factions."),
            EventType::WarDeclared,
            time,
        );
        event.participants = Some(vec![attacker_id, defender_id]);
        event.effects.push(EventEffect::BorderShift {
            from: None,
            to: defender_id,
            territory: attacker_id, // placeholder - would be actual territory
        });
        event.significance = Some(0.85);
        event
    }
    
    /// Create a plague/disaster event.
    pub fn plague(
        world_id: Uuid,
        plague_name: &str,
        affected_ids: Vec<Uuid>,
        time: HistoricalTime,
        duration_years: i32,
    ) -> Self {
        let end_year = time.get_year() + duration_years;  // Extract year before time moves
        let mut event = Self::new(
            world_id,
            plague_name.to_string(),
            format!("A devastating plague struck the region, lasting approximately {} years.", duration_years),
            EventType::Plague,
            time,
        );
        event.end_time = Some(HistoricalTime::year(end_year));
        event.participants = Some(affected_ids);
        event.significance = Some(0.80);
        event
    }
    
    /// Check if this event has ended.
    pub fn has_ended(&self) -> bool {
        self.end_time.is_some()
    }
    
    /// Get the duration of this event in years, if known.
    pub fn duration_years(&self) -> Option<i32> {
        match (self.time.get_year(), self.end_time.as_ref()?.get_year()) {
            (start, end) => Some(end - start),
            _ => None,
        }
    }
    
    /// Check if this event is historical (ended before current time).
    pub fn is_historical(&self) -> bool {
        self.has_ended()
    }
    
    /// Add a participant to this event.
    pub fn add_participant(&mut self, participant_id: Uuid) {
        match &mut self.participants {
            Some(participants) => {
                if !participants.contains(&participant_id) {
                    participants.push(participant_id);
                }
            }
            None => {
                self.participants = Some(vec![participant_id]);
            }
        }
        self.updated_at = Timestamp::now();
    }
    
    /// Add an effect to this event.
    pub fn add_effect(&mut self, effect: EventEffect) {
        self.effects.push(effect);
        self.updated_at = Timestamp::now();
    }
    
    /// Add a consequence to this event.
    pub fn add_consequence(&mut self, consequence: String) {
        match &mut self.consequences {
            Some(consequences) => {
                consequences.push(consequence);
            }
            None => {
                self.consequences = Some(vec![consequence]);
            }
        }
        self.updated_at = Timestamp::now();
    }
}

/// Builder for constructing events fluently.
#[derive(Debug, Clone)]
pub struct EventBuilder {
    name: String,
    description: String,
    event_type: Option<EventType>,
    time: Option<HistoricalTime>,
    end_time: Option<HistoricalTime>,
    location_id: Option<Uuid>,
    participants: Vec<Uuid>,
    effects: Vec<EventEffect>,
    significance: Option<f32>,
    sources: Vec<String>,
}

impl EventBuilder {
    /// Create a new event builder with required name field.
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            description: String::new(),
            event_type: None,
            time: None,
            end_time: None,
            location_id: None,
            participants: Vec::new(),
            effects: Vec::new(),
            significance: None,
            sources: Vec::new(),
        }
    }
    
    /// Set the event type.
    pub fn event_type(mut self, event_type: EventType) -> Self {
        self.event_type = Some(event_type);
        self
    }
    
    /// Set the event type using Into<EventType>.
    pub fn with_type(mut self, event_type: EventType) -> Self {
        self.event_type = Some(event_type);
        self
    }
    
    /// Set the time.
    pub fn time(mut self, time: HistoricalTime) -> Self {
        self.time = Some(time);
        self
    }
    
    /// Set the end time (for duration events).
    pub fn end_time(mut self, end_time: HistoricalTime) -> Self {
        self.end_time = Some(end_time);
        self
    }
    
    /// Set the description.
    pub fn description(mut self, description: impl Into<String>) -> Self {
        self.description = description.into();
        self
    }
    
    /// Set the description with a reason (appended to description).
    pub fn with_reason(mut self, reason: &str) -> Self {
        if !reason.is_empty() {
            if self.description.is_empty() {
                self.description = reason.to_string();
            } else {
                self.description.push_str(": ");
                self.description.push_str(reason);
            }
        }
        self
    }
    
    /// Set the location.
    pub fn location(mut self, location_id: Uuid) -> Self {
        self.location_id = Some(location_id);
        self
    }
    
    /// Add a participant.
    pub fn participant(mut self, participant_id: Uuid) -> Self {
        self.participants.push(participant_id);
        self
    }
    
    /// Add multiple participants.
    pub fn participants(mut self, participant_ids: impl IntoIterator<Item = Uuid>) -> Self {
        self.participants.extend(participant_ids);
        self
    }
    
    /// Add an effect.
    pub fn effect(mut self, effect: EventEffect) -> Self {
        self.effects.push(effect);
        self
    }
    
    /// Add multiple effects.
    pub fn effects(mut self, effects: impl IntoIterator<Item = EventEffect>) -> Self {
        self.effects.extend(effects);
        self
    }
    
    /// Set the significance (0.0 to 1.0).
    pub fn significance(mut self, significance: f32) -> Self {
        self.significance = Some(significance.clamp(0.0, 1.0));
        self
    }
    
    /// Add a source.
    pub fn source(mut self, source: impl Into<String>) -> Self {
        self.sources.push(source.into());
        self
    }
    
    /// Build the event.
    pub fn build(self, world_id: Uuid) -> Event {
        let time = self.time.expect("Event time is required");
        let event_type = self.event_type.expect("Event type is required");
        
        Event {
            id: EntityId::new(EntityType::Event),
            world_id,
            name: self.name,
            description: self.description,
            event_type,
            time,
            end_time: self.end_time,
            location_id: self.location_id,
            participants: if self.participants.is_empty() {
                None
            } else {
                Some(self.participants)
            },
            effects: self.effects,
            consequences: None,
            significance: self.significance,
            sources: if self.sources.is_empty() {
                None
            } else {
                Some(self.sources)
            },
            created_at: Timestamp::now(),
            updated_at: Timestamp::now(),
        }
    }
}

// Extend HistoricalTime with year accessor for EventBuilder
impl HistoricalTime {
    /// Get the year from a HistoricalTime.
    /// Returns the year for Year variants, or 0 for Relative/Unknown.
    pub fn get_year(&self) -> i32 {
        match self {
            HistoricalTime::Year { year, .. } => *year,
            HistoricalTime::Relative { years, .. } => *years,
            HistoricalTime::Unknown => 0,
        }
    }
}

// ============================================================================
// Event Collection & Storage
// ============================================================================

/// A collection of events with timeline ordering.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct EventStore {
    events: Vec<Event>,
}

impl EventStore {
    /// Create a new empty event store.
    pub fn new() -> Self {
        Self { events: Vec::new() }
    }
    
    /// Add an event to the store.
    pub fn add(&mut self, event: Event) {
        self.events.push(event);
    }
    
    /// Get all events.
    pub fn events(&self) -> &[Event] {
        &self.events
    }
    
    /// Get events mutable.
    pub fn events_mut(&mut self) -> &mut Vec<Event> {
        &mut self.events
    }
    
    /// Number of events.
    pub fn len(&self) -> usize {
        self.events.len()
    }
    
    /// Check if empty.
    pub fn is_empty(&self) -> bool {
        self.events.is_empty()
    }
    
    /// Get events by type.
    pub fn by_type(&self, event_type: EventType) -> Vec<&Event> {
        self.events.iter().filter(|e| e.event_type == event_type).collect()
    }
    
    /// Get events at a specific location.
    pub fn at_location(&self, location_id: Uuid) -> Vec<&Event> {
        self.events.iter()
            .filter(|e| e.location_id == Some(location_id))
            .collect()
    }
    
    /// Get events involving a participant.
    pub fn with_participant(&self, participant_id: Uuid) -> Vec<&Event> {
        self.events.iter()
            .filter(|e| e.participants.as_ref()
                .map(|p| p.contains(&participant_id))
                .unwrap_or(false))
            .collect()
    }
    
    /// Sort events chronologically.
    pub fn sort_chronologically(&mut self) {
        self.events.sort_by(|a, b| {
            match (a.time.get_year(), b.time.get_year()) {
                (ya, yb) if ya != yb => ya.cmp(&yb),
                _ => {
                    let sig_a = a.significance.unwrap_or(0.5);
                    let sig_b = b.significance.unwrap_or(0.5);
                    sig_b.partial_cmp(&sig_a).unwrap()
                }
            }
        });
    }
    
    /// Get events within a year range.
    pub fn in_range(&self, start_year: i32, end_year: i32) -> Vec<&Event> {
        self.events.iter()
            .filter(|e| {
                let year = e.time.get_year();
                year >= start_year && year <= end_year
            })
            .collect()
    }
    
    /// Get the earliest event year.
    pub fn earliest_year(&self) -> Option<i32> {
        self.events.iter()
            .map(|e| e.time.get_year())
            .filter(|&y| y > 0)
            .min()
    }
    
    /// Get the latest event year (considering end_time for ongoing events).
    pub fn latest_year(&self) -> Option<i32> {
        self.events.iter()
            .map(|e| e.end_time.as_ref()
                .map(|t| t.get_year())
                .unwrap_or(e.time.get_year()))
            .filter(|&y| y > 0)
            .max()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn test_event_creation() {
        let event = Event::new(
            Uuid::new_v4(),
            "Test Event".to_string(),
            "A test event description.".to_string(),
            EventType::Discovery,
            HistoricalTime::year(1492),
        );
        
        assert_eq!(event.name, "Test Event");
        assert!(matches!(event.event_type, EventType::Discovery));
        assert_eq!(event.effects.len(), 0);
    }
    
    #[test]
    fn test_settlement_founded_event() {
        let world_id = Uuid::new_v4();
        let settlement_id = Uuid::new_v4();
        
        let event = Event::settlement_founded(
            world_id,
            settlement_id,
            "New Hope",
            HistoricalTime::year(1776),
        );
        
        assert!(event.name.contains("New Hope"));
        assert!(matches!(event.event_type, EventType::SettlementFounded));
        assert!(event.participants.as_ref().map_or(false, |p| p.contains(&settlement_id)));
    }
    
    #[test]
    fn test_event_builder() {
        let world_id = Uuid::new_v4();
        let settlement_id = Uuid::new_v4();
        let nation_id = Uuid::new_v4();
        
        let event = EventBuilder::new("The Great Migration")
            .event_type(EventType::Migration)
            .time(HistoricalTime::year(1200))
            .location(settlement_id)
            .participant(settlement_id)
            .participant(nation_id)
            .effect(EventEffect::PopulationShift {
                from: settlement_id,
                to: nation_id,
                count: 5000,
                cause: None,
            })
            .significance(0.75)
            .build(world_id);
        
        assert_eq!(event.name, "The Great Migration");
        assert!(matches!(event.event_type, EventType::Migration));
        assert_eq!(event.participants.as_ref().map(|p| p.len()), Some(2));
        assert_eq!(event.effects.len(), 1);
        assert_eq!(event.significance, Some(0.75));
    }
    
    #[test]
    fn test_event_store_operations() {
        let world_id = Uuid::new_v4();
        let mut store = EventStore::new();
        
        store.add(Event::settlement_founded(world_id, Uuid::new_v4(), "Town A", HistoricalTime::year(100)));
        store.add(Event::settlement_founded(world_id, Uuid::new_v4(), "Town B", HistoricalTime::year(200)));
        store.add(Event::war_declared(world_id, "The Great War", Uuid::new_v4(), Uuid::new_v4(), HistoricalTime::year(150)));
        
        assert_eq!(store.len(), 3);
        assert_eq!(store.by_type(EventType::SettlementFounded).len(), 2);
        assert_eq!(store.by_type(EventType::WarDeclared).len(), 1);
        
        store.sort_chronologically();
        let events = store.events();
        assert_eq!(events[0].time.get_year(), 100);
        assert_eq!(events[1].time.get_year(), 150);
    }
    
    #[test]
    fn test_historical_time_year() {
        assert_eq!(HistoricalTime::year(1000).get_year(), 1000);
        assert_eq!(HistoricalTime::date(2024, 1, 15).get_year(), 2024);
        assert_eq!(HistoricalTime::Unknown.get_year(), 0);
    }
}